question_data = [{"type":"boolean",
                   "difficulty":"easy",
                   "category":"General Knowledge",
                   "question":"Scotland voted to become an independent country during the referendum from September 2014.",
                   "correct_answer":"False",
                   "incorrect_answers":["True"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"The Sun rises from the North.",
                  "correct_answer":"False",
                  "incorrect_answers":["True"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                  "correct_answer":"True",
                  "incorrect_answers":["False"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                  "correct_answer":"False","incorrect_answers":["True"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"When you cry in space, your tears stick to your face.",
                  "correct_answer":"True",
                  "incorrect_answers":["False"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"French is an official language in Canada.",
                  "correct_answer":"True",
                  "incorrect_answers":["False"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"Jingle Bells was originally meant for Thanksgiving",
                  "correct_answer":"True","incorrect_answers":["False"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"Ping-Pong originated in England",
                  "correct_answer":"True",
                  "incorrect_answers":["False"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                  "correct_answer":"True"
                  ,"incorrect_answers":["False"]},
                  {"type":"boolean",
                  "difficulty":"easy",
                  "category":"General Knowledge",
                  "question":"The National Animal of Scotland is the Unicorn.",
                  "correct_answer":"True",
                  "incorrect_answers":["False"]}]